### ISSUE TITLE
Using RTSP simulator with grpn end of video pauses the pipeline for 1 mins

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#15]
Issue:: Using rtspsim to simulate video-based feedback loop after completion of video, gRPC based system the device takes 1 min pause at end of video

How to repro : 
deploy vision on edge form here https://github.com/Azure-Samples/azure-intelligent-edge-patterns/tree/master/factory-ai-vision

try running the box-counting scenario 

Expected::
the video should loop with minimum delay or pause

actual ::
Video pause for more than a mniute before restarting

**Comment by mustafakasap** [comment]
This issue is answered in https://github.com/Azure-Samples/live-video-analytics-iot-edge-python/issues/16 

it is related with Live555 sample simulator and recommendation is to use longer duration video files for your simulations. With real IP Cameras you will not face such issues unless there is network disconnection like issue.

**Comment by initmahesh** [comment]
thanks got this..!!
