### ISSUE TITLE
Adapting frame rate dynamically based on no. cameras and speed of ai results

### ISSUE THREAD

**Issue by initmahesh** [Azure-Samples/live-video-analytics-iot-edge-python#18]
:: as we increase the camera we need to decide as what the frame rate that can be supported by the hardware,
the current way is to guess or hardcode this needs to be dynamic by LVA based on what can be supported based on feedback from AI module and system capability by using some calibration.

As LVA grpc start dropping frames the user believes they are doing 30 fps while the real maybe only 2 fps, how can at ai module as what is current fps base don no. of camera`s

**Comment by mustafakasap** [comment]
In your deployment manifest, If you assign the same lvaExtension address for each camera source to make inference, than you can write a HTTP (similar approach exists also for gRPC) query string. i.e. in your manifest, you have two camera each calling the inference server at address: http://lvaExtension:44000/score

instead of using above address as is for all cameras, use:
http://lvaExtension:44000/score?cam=1    (i.e. for first camera)
http://lvaExtension:44000/score?cam=2    (i.e. for second camera)


inside the lvaExtension code, read the query string to decide which camera sends the frame in.  Rest is simple as computing the previous and current frame receipt time stamp difference and calculate frames sent per second per camera... you can output these numbers in your logs, or publish to event hub or server from the module from specific port number.

**Comment by initmahesh** [comment]
more clarification:: 
the user is using one camera at 30 fps , if they add more cameras how can they know when they add the camera`s as what fps they can support on there specific ai model, as the inference can be calculating we need a way to dynamically adapt frame filter based on no. of camera used ...
